# Generated by Django 4.2.4 on 2023-08-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
